apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-pod
  labels:
    app: lab2
spec:
  containers:
  - image: busybox
    name: my-configmap-pod
    command: ['sh' , '-c' , 'echo $(KEY1) && sleep 3600']
    env:
    - name: KEY1
      valueFrom:
        configMapKeyRef:
          name: my-config-map
          key: key1
