apiVersion: v1
kind: Pod
metadata:
  name: my-resource-pod
  labels:
    app: lab2
spec:
  containers:
  - image: busybox
    name: my-resource-container
    command: ['sh', '-c', 'echo Hi from resources pod && sleep 3600']
    resources:
      requests:
        cpu: 250m
        memory: 64M
      limits:
        cpu: 1.0
        memory: 256Mi
