apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hostpath-volume-pod
spec:
  selector:
    matchLabels:
      app: hostpath
  template:
    metadata:
      labels:
        app: hostpath
    spec:
      containers:
        - name: main
          image: busybox
          args:
            - sh
            - -c
            - sleep 3600
          volumeMounts:
            - name: node-hostpath
              mountPath: /data
      volumes:
        - name: node-hostpath
          hostPath:
            path: "/mnt/data"
