apiVersion: v1
kind: ConfigMap
metadata:
  name: lab2-configmap
data:
  key1: value1
  key2: value2
  key3: value3
---
apiVersion: v1
kind: Secret
metadata: 
  name: lab2-secret
stringData:
  pswKey: passwordValue
---
apiVersion: v1
kind: Pod
metadata:
  name: lab2-pod
  labels:
    app: config-training
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 0
#    runAsNonRoot: true
  containers:
  - image: busybox
    name: mylab2-container
    command: ['sh' , '-c' , 'echo $(KEY1) with password: $(PSW) && sleep 3600']
    env:
    - name: KEY1
      valueFrom:
        configMapKeyRef:
          name: lab2-configmap
          key: key1
    - name: PSW
      valueFrom:
        secretKeyRef:
          name: lab2-secret
          key: pswKey
    resources:
      requests:
        cpu: 300m
        memory: 64M
      limits: 
        cpu: 1.0
        memory: 256Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: lab2-volume-pod
  labels:
    app: lab2
spec:
  restartPolicy: Never
  containers:
  - image: busybox
    name: lab2-volume-pod-container
    command: ['sh' , '-c' , 'echo $(cat /etc/config/key_1) && sleep 3600']
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: lab2-configmap
      items:
      - key: key1
        path: key_1
      - key: key2
        path: key_2
