apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: my-ns
  labels:
    app: myapp
spec:
  containers:
  - image: busybox
    name: my-pod
    command: ['sh', '-c-', 'echo Hello Kubernetes! && sleep 3600']
