apiVersion: v1
kind: Pod
metadata:
  name: my-args-pod
  labels:
    app: myapp
spec:
  containers:
  - image: busybox
    name: my-pod
    command: ['echo']
    args: ['Hello World!']
  restartPolicy: Never
