apiVersion: v1
kind: Pod
metadata:
  name: nginx-prod
  labels:
    app: nginx
    env: prod
  annotations:
    owner: kulinskyvs@gmail.com
    vendor: My Company
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-dev
  labels:
    app: nginx
    env: dev
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80        
