apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    app: candy-ws
  name: candy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candy-ws
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: candy-ws
    spec:
      containers:
      - image: linuxacademycontent/candy-service:2
        imagePullPolicy: IfNotPresent
        name: candy-ws
      restartPolicy: Always
